### PR TITLE
Use descriptors for column binding information

### LINKED ISSUE #235: Represent column bindings through corresponding descriptors
Currently, it is done in an ad-hoc manner, which significantly reduces ability to add many features associated with advanced (batch) fetches etc.

### LINKED ISSUE #296: Не получается выгрузить данные из Clickhouse через SSIS пакет
Clickhouse версии 20.3.8.53
Visual Studio 2019
odbc driver 1.1.7 x32 (win)
Настроил odbc driver - в SystemDSN добавил драйвер 32 bit (Clickhouse ODBC driver Unicode), указал хост, порт и базу.
Сделал простейший SSIS пакет. Забрать данные из ODBC Source и положить в SQL Server
При настройке ODBC Source проблем не было: таблица из Clickhouse видна, колонки ее видны и Preview работает - показывает данные из таблицы из Clickhouse

Но при собственно запуске пакета на выполнение из студии - ошибка на шаге "ODBC Source"

В логе Clickhouse есть вот такое:

2020.05.27 09:30:39.292148 [ 9891 ] {caad6f82-4855-4a5d-8c37-e26785d03153} <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof (version 20.3.8.53)

При включении трассировки odbc вот такое можно заметить:

DtsDebugHost    2d2c-3a94	EXIT  SQLExecute  with return code -1 (SQL_ERROR)
		HSTMT               0x08B35058
		DIAG [HY000] statement not prepared (1) 

Подскажите, пожалуйста, что можно сделать, чтобы отработал ssis пакет? Недонастроил я может быть что-то?

### PR DESCRIPTION
**Pull request by traceon**
Use descriptors for column binding information.
Fix column-wise vs row-wise binding for parameters and implement it for columns.
Implement array bindings for columns.

Closes #235
Closes #296
Doc modification reflects findings in #293
Doc modification reflects versioning issues mentioned in #289
Should help with #299
Should help with #295

### CODE REVIEW

File: driver/api/impl/impl.cpp [hunk 1]
```diff
@@ -659,6 +730,34 @@ SQLRETURN BindParameter(
...
+            StrLen_or_IndPtr == nullptr &&
+            parameter_number >= apd_record_count
+        ) {
+            auto nextHighestBoundParameterNumber = std::min<std::size_t>(apd_record_count, parameter_number - 1);
+
+            while (nextHighestBoundParameterNumber > 0) {
+                auto & apd_record = apd_desc.getRecord(nextHighestBoundParameterNumber, SQL_ATTR_APP_PARAM_DESC);
+
+                if (
+                    apd_record.getAttrAs<SQLPOINTER>(SQL_DESC_DATA_PTR, 0) != nullptr ||
```
Comment (Enmk) [inline driver/api/impl/impl.cpp:747]: Finding the latest bound parameter (one with non-null data ptr or length ptr, or indicator ptr)

File: driver/api/impl/impl.cpp [hunk 2]
```diff
@@ -1151,6 +1245,10 @@ SQLRETURN fillBinding(
         binding_info.c_type = record.getAttrAs<SQLSMALLINT>(SQL_DESC_CONCISE_TYPE, SQL_C_DEFAULT);
     }
 
+    if (binding_info.c_type == SQL_C_DEFAULT) {
+        binding_info.c_type = convertSQLTypeToCType(statement.getTypeInfo(result_set.getColumnInfo(column_idx).type_without_parameters).sql_type);
```
Comment (Enmk) [inline driver/api/impl/impl.cpp:1249]: Could you accidentally end up with `SQL_C_DEFAULT` as a result? Is that an error ?

File: driver/api/impl/impl.cpp [hunk 3]
```diff
@@ -1166,74 +1264,212 @@ SQLRETURN fillBinding(
...
+        }
+
         return SQL_NO_DATA;
     }
 
     if (rows_fetched_ptr)
         *rows_fetched_ptr = rows_fetched;
 
-    auto res = SQL_SUCCESS;
+    const auto ard_record_count = ard_desc.getRecordCount();
```
Comment (Enmk) [inline driver/api/impl/impl.cpp:1310]: can count and container somehow diverge ?

File: driver/api/impl/impl.cpp (hunk 2 above)
Comment (traceon) [reply driver/api/impl/impl.cpp:1249]: In practice, that won't happen. Column info is populated from the query execution info, and unknown types are detected there. In theory, `SQL_C_DEFAULT` will result in hard error during data extraction, so will be detected and reported in one form or another.

File: driver/api/impl/impl.cpp (hunk 1 above)
Comment (traceon) [reply driver/api/impl/impl.cpp:747]: Is you message truncated?

File: driver/api/impl/impl.cpp (hunk 3 above)
Comment (traceon) [reply driver/api/impl/impl.cpp:1310]: No, that is ensured exactly by the next line.

File: driver/api/impl/impl.cpp (hunk 1 above)
Comment (Enmk) [reply driver/api/impl/impl.cpp:747]: sorry, that was an intermediate note for myself

File: driver/api/impl/impl.cpp (hunk 2 above)
Comment (Enmk) [reply driver/api/impl/impl.cpp:1249]: Is there any test you can make to validate that it will be handled properly ?

Comment (traceon) [reply driver/api/impl/impl.cpp:1249]: Not in C++ client tests.

File: driver/test/column_bindings_it.cpp [hunk 4]
```diff
@@ -0,0 +1,487 @@
...
+    FixedStringBuffer() {
+        // Fill with a special placeholder sequence.
+        std::fill(data, data + Size, 0b11011011);
+    }
+
+    CharType data[Size];
+};
+
+TEST_P(ColumnArrayBindingsTest, ColumnWise) {
+    const std::size_t total_rows_expected = std::get<1>(GetParam());
```
Comment (Enmk) [inline driver/test/column_bindings_it.cpp:30]: Could you please outline the test purpose and major points in the function-level comment, something like:
Bind various columns of fixed size, emulate a query, and validate that indices/offsets are valid.

Otherwise, it is really hard to decode your intent.

File: driver/test/column_bindings_it.cpp [hunk 5]
```diff
@@ -0,0 +1,487 @@
...
+
+        if (rc == SQL_SUCCESS_WITH_INFO)
+            std::cout << extract_diagnostics(hstmt, SQL_HANDLE_STMT) << std::endl;
+
+        if (!SQL_SUCCEEDED(rc))
+            throw std::runtime_error("SQLFetch return code: " + std::to_string(rc));
+
+        ASSERT_LE(rows_processed, array_size);
+
+        for (std::size_t i = 0; i < array_size; ++i) {
```
Comment (Enmk) [inline driver/test/column_bindings_it.cpp:192]: Same thing here: there are some not so easily guessable assumptions about results.

File: driver/utils/type_info.h [hunk 6]
```diff
@@ -1813,6 +1813,9 @@ namespace value_manip {
         template <typename SourceType>
         struct from_value {
             static inline SQLRETURN convert(const SourceType & src, BindingInfo & dest) {
+                if (dest.indicator && dest.indicator != dest.value_size)
+                    *dest.indicator = 0; // Value is not null here...
```
Comment (Enmk) [inline driver/utils/type_info.h:1817]: Not quite sure what `indicator` means here, could you please add some comments to `BindingInfo`? Please also specify what does it mean when `indicator` value is `0`.

File: driver/test/column_bindings_it.cpp [hunk 7]
```diff
@@ -0,0 +1,487 @@
...
+            adjsut_ptr(&col6[0]),
+            sizeof(col6[0]),
+            adjsut_ind_ptr(&col6_ind[0])
+        )
+    );
+
+    std::size_t total_rows = 0;
+
+    while (true) {
+        // Must not reallocate the underlying buffers.
```
Comment (Enmk) [inline driver/test/column_bindings_it.cpp:154]: Why ?

File: driver/test/column_bindings_it.cpp [hunk 8]
```diff
@@ -0,0 +1,487 @@
...
+    };
+
+    std::vector<SQLINTEGER> col1(array_size);
+    std::vector<SQLLEN> col1_ind(array_size);
+
+    ODBC_CALL_ON_STMT_THROW(hstmt,
+        SQLBindCol(
+            hstmt,
+            1,
+            getCTypeFor<std::decay_t<decltype(col1[0])>>(),
```
[the remark this answers is not in the document]
Comment (traceon) [reply driver/test/column_bindings_it.cpp:74]: The current `getCTypeFor` definition will cause the code to fail at compilation, so it is safe. Ugly here, but safe everywhere.

File: driver/test/column_bindings_it.cpp (hunk 4 above)
Comment (traceon) [reply driver/test/column_bindings_it.cpp:34]: Added comments.

File: driver/test/column_bindings_it.cpp (hunk 5 above)
Comment (traceon) [reply driver/test/column_bindings_it.cpp:206]: Added comments about what is happening in general.

File: driver/utils/type_info.h (hunk 6 above)
Comment (traceon) [reply driver/utils/type_info.h]: Modified the comments.

File: driver/test/column_bindings_it.cpp (hunk 7 above)
Comment (traceon) [reply driver/test/column_bindings_it.cpp]: Added comments.
