### PR TITLE
Switch to ClickHouse version 20.3 as a baseline (changes NULL param string format)

### LINKED ISSUE #236: Phase in support of recent changes of NULL representation/parsing at server side
The changes were implemented in the scope of https://github.com/ClickHouse/ClickHouse/issues/7488

### LINKED ISSUE #294: Проблемы с прохождением тестов после сборки clickhouse-odbc
Pre-build пакеты предлагаемые [здесь](https://github.com/ClickHouse/clickhouse-odbc/releases) собраны с использованием libicu50, которая отсутствует в репозиториях Ubuntu. Я собрал clickhouse-odbc с libicu66, но тесты
```
4 - clickhouse-odbc-client-it-dsn-0
5 - clickhouse-odbc-client-it-dsn-1
11 - clickhouse-odbcw-client-it-dsn-0
12 - clickhouse-odbcw-client-it-dsn-1
```
провалились.

Ошибки из логов:
```
[----------] 4 tests from StatementParametersTest
[ RUN      ] StatementParametersTest.BindingMissing
unknown file: Failure
C++ exception with description "1:[HY000][1]HTTP status code: 501
Received error:
Code: 48, e.displayText() = DB::Exception: Serialization is not implemented for data type Nothing (version 20.3.8.53 (official build))

" thrown in the test body.
[  FAILED  ] StatementParametersTest.BindingMissing (7 ms)
[ RUN      ] StatementParametersTest.BindingNoBuffer
unknown file: Failure
C++ exception with description "1:[HY000][1]HTTP status code: 500
Received error:
Code: 457, e.displayText() = DB::Exception: Value Null cannot be parsed as Nullable(Int32) for query parameter 'odbc_positional_1' because it isn't parsed completely: only 0 of 4 bytes was parsed: (version 20.3.8.53 (official build))

" thrown in the test body.
[  FAILED  ] StatementParametersTest.BindingNoBuffer (4 ms)
[ RUN      ] StatementParametersTest.BindingNullStringValueForInteger
unknown file: Failure
C++ exception with description "1:[HY000][1]HTTP status code: 500
Received error:
Code: 457, e.displayText() = DB::Exception: Value Null cannot be parsed as Nullable(Int32) for query parameter 'odbc_positional_1' because it isn't parsed completely: only 0 of 4 bytes was parsed: (version 20.3.8.53 (official build))

" thrown in the test body.
[  FAILED  ] StatementParametersTest.BindingNullStringValueForInteger (4 ms)
[ RUN      ] StatementParametersTest.BindingNullStringValueForString
/home/cyalat3r/clickhouse-odbc/driver/test/statement_parameters_it.cpp:261: Failure
Expected equality of these values:
  col
    Which is: 0
  1
[  FAILED  ] StatementParametersTest.BindingNullStringValueForString (3 ms)
[----------] 4 tests from StatementParametersTest (18 ms total)
```
Остальные тесты проходит, через isql коннектится.

### PR DESCRIPTION
**Pull request by traceon**
Closes #236
Closes #294
May help with #298 too

This changes are reflecting the following changes in ClickHouse server parameter parsing behavior: https://github.com/ClickHouse/ClickHouse/issues/7488 and https://github.com/ClickHouse/ClickHouse/pull/8517

### CODE REVIEW

**Comment by traceon** [comment]
`parametrized-regression.py-3-dsn-*` tests failures can be ignored here, they are addressed separately by #303

File: driver/statement.cpp [hunk 1]
```diff
@@ -307,7 +307,7 @@ std::string Statement::buildFinalQuery(const std::vector<ParamBindingInfo>& para
         std::string param_type;
 
         if (param_bindings.size() <= i) {
-            param_type = "Nullable(Nothing)";
+            param_type = "Nullable(String)";
```
Comment (filimonov) [inline driver/statement.cpp:310]: I don't get this one. 

Also check comment
https://github.com/ClickHouse/clickhouse-odbc/blob/3b61ca7b2050f042da1d7faabb3d23b6627a4200/driver/statement.cpp#L435

File: driver/test/statement_parameters_it.cpp [hunk 2]
```diff
@@ -122,7 +122,7 @@ TEST_F(StatementParametersTest, BindingNullStringValueForInteger) {
 #    define SQL_C_myTCHAR SQL_C_TCHAR
 #endif
 
-    auto param = fromUTF8<SQLmyTCHAR>("Null");
+    auto param = fromUTF8<SQLmyTCHAR>("\\N");
```
Comment (filimonov) [inline driver/test/statement_parameters_it.cpp:125]: Update the PR name / desciption if you want to fix that in that PR. 

BTW - is there any tests for that functionality?

File: test/deploy_and_run_clickhouse_macos.sh [hunk 3]
```diff
@@ -17,12 +17,13 @@ echo 1. Prepare folders
 mkdir -p usr/bin etc/clickhouse-server var/lib/clickhouse
 
 echo 2. Download binaries
-curl https://clickhouse-builds.s3.yandex.net/0/381947509a4f66236f943beaefb0b1f5c2fd979d/1570028580_binary/clickhouse -o usr/bin/clickhouse
-curl https://clickhouse-builds.s3.yandex.net/0/381947509a4f66236f943beaefb0b1f5c2fd979d/1570028580_binary/clickhouse-odbc-bridge -o usr/bin/clickhouse-odbc-bridge
+# TODO: switch to actual 20.3 binaries once available. Currently, this is master branch.
+curl https://clickhouse-builds.s3.yandex.net/0/d147cd646a1e6cc41d42f92d57f016a5c49d04de/clang-10-darwin_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse -o usr/bin/clickhouse
+curl https://clickhouse-builds.s3.yandex.net/0/d147cd646a1e6cc41d42f92d57f016a5c49d04de/clang-10-darwin_relwithdebuginfo_none_bundled_unsplitted_disable_False_binary/clickhouse-odbc-bridge -o usr/bin/clickhouse-odbc-bridge
```
Comment (filimonov) [inline test/deploy_and_run_clickhouse_macos.sh:22]: Just after our talk yesterday Yandex guys added that: 
https://github.com/ClickHouse/ClickHouse/pull/11889/files

But let's leave it as is for now.

File: test/deploy_and_run_clickhouse_macos.sh [hunk 4]
```diff
@@ -17,12 +17,13 @@ echo 1. Prepare folders
...
 
 echo 3. Download configs
-curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/v20.1.9.54-stable/dbms/programs/server/config.xml -o etc/clickhouse-server/config.xml
-curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/v20.1.9.54-stable/dbms/programs/server/users.xml -o etc/clickhouse-server/users.xml
+curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/20.3/programs/server/config.xml -o etc/clickhouse-server/config.xml
+curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/20.3/programs/server/users.xml -o etc/clickhouse-server/users.xml
```
Comment (filimonov) [inline test/deploy_and_run_clickhouse_macos.sh:26]: Since we have 20.5 binary for Mac, it's also better to take 20.5 default configs. 

```suggestion
curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/20.5/programs/server/config.xml -o etc/clickhouse-server/config.xml
curl https://raw.githubusercontent.com/ClickHouse/ClickHouse/20.5/programs/server/users.xml -o etc/clickhouse-server/users.xml
```

File: driver/test/statement_parameters_it.cpp (hunk 2 above)
Comment (traceon) [reply driver/test/statement_parameters_it.cpp:125]: Yes, this is a fix of those test, that fail with new server.

File: driver/statement.cpp (hunk 1 above)
Comment (traceon) [reply driver/statement.cpp:310]: Updated.

File: test/deploy_and_run_clickhouse_macos.sh (hunk 3 above)
Comment (traceon) [reply test/deploy_and_run_clickhouse_macos.sh:22]: I checked the link, they don't have `.../20.3/...` binary there, looks like.
